spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_product?useSSL=false&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    EnableZoneAffinity: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
management:
  security:
    enabled: false

endpoints:
  actuator:
    enabled: true